version: '3'
services:
  server:
    container_name: server
    build:
      context: ./server
    restart: always
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./server:/server:cached
      - .env:/server/.env
